---
title: "Local bodies extended"
author: ""
date: "11/09/20"
params:
  orig_date: "Original Publish Date: 11 September, 2020"
  update_date: !r paste("Updated on:", format(Sys.time(), '%d %B, %Y'))
output:
  html_document:
    theme: readable
    toc: TRUE
    toc_float: TRUE
    toc_depth: 5
    number_sections: false
    fig_width: 6            
editor_options: 
  chunk_output_type: inline

---

---

### Document History

`r params$orig_date`

`r params$update_date`

---
```{r set up, warning=FALSE, include=FALSE, message= FALSE}

knitr::opts_chunk$set(cache = FALSE,echo = FALSE, message=FALSE, warning = FALSE,fig.width = 16/2, fig.height = 9/2)


library(tidyverse)
library(data.table)
library(knitr)
library(kableExtra)
library(scales)
library(gridExtra)
library(stargazer)
library(ggbump)
`%!in%` = Negate(`%in%`)

select <- dplyr::select
```

<!-- In this post we will be looking at dynasticism at the local level. We will be using two different definitions. 1 - category 2 - Where we only consider if an individual/set of individuals have connections to the ae-ge level. 2 - category 4 - We consider them as a dynast as long as they have/ have had members at one of the levels. -->


## Summary {.tabset}


### All years


**Break-up of dynast representatives in local body data**

```{r}
dyn_all <-  read.csv("D:/cpr/UP/up-dynasties/dyn_other_data/dyn_all.csv")


dyn_lb <- dyn_all %>% filter(election_type %!in% c("AE", "GE"))


dyn_lb %>%filter(position ==1)%>% group_by(election_type) %>% summarise(count = n(), dyn= sum(dyn_cum_4), pc= round(dyn/count*100)) %>% 
  select(election_type, pc) %>% kable(col.names = c("Election", "Dynast %")) %>% kable_styling(full_width = F)



```

### year by eyar


```{r}




cp1 <- dyn_lb %>%filter(position ==1 & election_type %in% c("BP","ZP"))%>% group_by(election_type, year) %>% summarise(count = n(), dyn= sum(dyn_cum_4), pc= dyn/count) %>% 
  ggplot(aes(factor(year), pc, group=election_type))+
 geom_line(size = 1, aes(linetype = election_type))+
  labs(subtitle = "Rural local bodies", x= "", y = "Percentage")+
  colorspace::scale_color_discrete_qualitative(palette = "dark3")+
  geom_point()+
  ylim(0,.4)+
  theme_bw()+
    theme(#legend.position = "bottom",
        axis.line.x= element_line(color = "gray50", size = .5),
        panel.grid.major.x  = element_blank(),
        panel.grid.minor   = element_blank(),
        axis.title.y = element_blank()
        
  )

cp2 <- dyn_lb %>%filter(position ==1 & election_type %!in% c("BP","ZP"))%>% group_by(election_type, year) %>% summarise(count = n(), dyn= sum(dyn_cum_4), pc= dyn/count) %>% 
  ggplot(aes(factor(year), pc, group=election_type))+
  geom_line(size = 1, aes(linetype = election_type))+
  labs(subtitle = "Urban local bodies", x= "Year", y = "Percentage")+
  colorspace::scale_color_discrete_qualitative(palette = "dark3")+
  geom_point()+
  ylim(0,.4)+
  theme_bw()+
    theme(#legend.position = "bottom",
        axis.line.x= element_line(color = "gray50", size = .5),
        panel.grid.major.x  = element_blank(),
        panel.grid.minor   = element_blank(),
        axis.title.y = element_blank()
        
  )


p5 <- cp1/cp2 
ggsave("D:/cpr/thesis/figures/fig_1_5.png", p5,width = 4, height =5, dpi = 300, units ="in" )


```



## Caste {.tabset}

### All representatives




```{r}

dyn_lb$caste_groups <- factor(dyn_lb$caste_groups, levels = c("Upper Caste","Yadav","Non-Yadav OBC","Dalit" , "Muslim"  ,"Others" ))

dyn_lb %>% filter(election_type!= "NN" & !is.na(caste_groups)) %>% group_by(election_type, caste_groups) %>% summarise(count = n()) %>% group_by(election_type) %>% mutate(sum = sum(count), pc = count/sum*100) %>% 
  ggplot(aes(election_type,pc, fill = caste_groups))+
      geom_bar(stat= "identity") +
    geom_text(size = 2.5, position = position_stack(vjust = 0.5), aes(label =round( pc,0)))+
    colorspace::scale_fill_discrete_qualitative(palette= "dark3" )+
    theme_minimal()+
labs(title = "Caste composition of local body representatives ",x = "", y = "" ,fill = "Caste Groups", subtitle = "In percentage")+
    theme(plot.margin = unit(c(.5,.5,.5,.5), "cm"))+
  theme(plot.background = element_blank(),
        axis.line.x = element_line(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.y = element_blank()
  ) 

```


### Families


```{r}

dyn_lb$caste_groups <- factor(dyn_lb$caste_groups, levels = c("Upper Caste","Yadav","Non-Yadav OBC","Dalit" , "Muslim"  ,"Others" ))

dyn_lb %>% filter(election_type!= "NN" & !is.na(caste_groups)& dyn_cum_4 == 1) %>% group_by(election_type, caste_groups) %>% summarise(count = n()) %>% group_by(election_type) %>% mutate(sum = sum(count), pc = count/sum*100) %>% 
  ggplot(aes(election_type,pc, fill = caste_groups))+
      geom_bar(stat= "identity") +
    geom_text(size = 2.5, position = position_stack(vjust = 0.5), aes(label =ifelse(pc>4,round(pc,0),"")))+
    colorspace::scale_fill_discrete_qualitative(palette= "dark3" )+
    theme_minimal()+
labs(title = "Caste composition of local body representatives ",x = "", y = "" ,fill = "Caste Groups", subtitle = "In percentage")+
  theme(plot.margin = unit(c(.5,.5,.5,.5), "cm"))+
  theme(plot.background = element_blank(),
        axis.line.x = element_line(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.y = element_blank()
  ) 

```



